Opp1213
navikt/modiapersonoversikt pull request #1352
Opened 2020-08-14 13:56 UTC by janeirik

ekstra sjekk på spørsmål og refaktorering av tester

2020-08-17 06:35 UTC, nutgaard commented on package.json
> +        "nav-frontend-core": "^4.0.13",
Dette er vel en nedgradering? Fra 5.0.1 til 4.0.13?

2020-08-17 06:36 UTC, nutgaard commented on package.json
> +        "nodejs": "0.0.0",
`node` og `nodejs` trenger vel ikke ligge her?

2020-08-20 13:32 UTC, tadeankur requested changes

2020-08-20 13:32 UTC, tadeankur commented on src/app/personside/kontrollsporsmal/SporsmalExtractors.tsx
> +    if (barn.tilPerson.personstatus.dødsdato) {
i Java man returnerer ikke true false  men boolean expression gjør det. Kan du sjekke hvis samme mulighet i typescript

2020-08-20 16:59 UTC, nutgaard commented on package.json
> +        "downshift": "^5.4.7",
Husk å sjekke autocomplete-dropdowns i OpprettOppgave når det er såpass stor bump av versjon

2020-08-20 17:01 UTC, nutgaard requested changes
Ser ut til å være noe krøll med en eller merge, slik at noen filer blir slettet.

2020-08-20 17:01 UTC, nutgaard commented on src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx
> +function fordelSaker(saker: JournalforingsSak[]): Kategorier {
Henger sammen med sletting av `VelgSak.test.ts`

2020-08-20 17:01 UTC, nutgaard commented on src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx.rej
> +diff a/src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx b/src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx	(rejected
I samme commit som `VelgSak.test.ts` ble lagt til, så ble denne slettet.

2020-08-21 08:22 UTC, closed without merging