[PROD][OPP-1249] Søk på utenlandsk ID
navikt/modiapersonoversikt pull request #1391
Opened 2020-10-20 13:57 UTC by vildestefferud

2020-10-21 07:04 UTC, olofab commented on src/app/personsok/PersonsokSkjema.tsx
> +            _minimumskrav = 'Du må minimum fylle inn navn, adresse, kontonummer eller utenlandsk ID for å gjøre søk';
Denne gjelder vel ikke før vi har skrudd på FT? Men bra å legge det inn her også ja!

2020-10-21 07:25 UTC, vildestefferud commented on src/app/personsok/PersonsokSkjema.tsx
> +            _minimumskrav = 'Du må minimum fylle inn navn, adresse, kontonummer eller utenlandsk ID for å gjøre søk';
Fikset det nå 🙂

2020-10-21 07:28 UTC, olofab submitted a review, later dismissed

2020-10-21 08:20 UTC, nutgaard requested changes
Vi må vente litt på utsending av infomasjon.

2020-10-22 12:18 UTC, vildestefferud commented
Søk med utenlandsk ID:
![image](https://user-images.githubusercontent.com/33753494/96870474-3e0f9280-1471-11eb-8d0d-980119bd04a8.png)

Søk på noe annet enn utenlandsk ID
![image](https://user-images.githubusercontent.com/33753494/96870594-6ac3aa00-1471-11eb-8bad-dea04c0d653d.png)

Med FT:
![image](https://user-images.githubusercontent.com/33753494/96870634-7b742000-1471-11eb-8632-494de9876c42.png)

2020-10-22 12:28 UTC, vildestefferud commented
Søk på utenlandsk ID (med mock-data): 

![image](https://user-images.githubusercontent.com/33753494/96871611-d1959300-1472-11eb-9183-615a019ba770.png)

2020-11-02 07:27 UTC, nutgaard approved these changes

2020-11-02 07:27 UTC, merged