[OPP-1153] henter vergemål fra pdl
navikt/modiapersonoversikt pull request #1477
Opened 2021-02-19 12:44 UTC by vildestefferud

2021-02-22 09:02 UTC, olofab commented on src/app/personside/visittkort/body/vergemal/Vergemal.tsx
> +function getPeriodeTekst(gyldighetstidspunkt?: string, opphoerstidspunkt?: string) {
`gyldighetsTidspunkt` og `opphoersTidspunk` kanskje? Litt lettere å lese med camelcase

2021-02-22 13:35 UTC, olofab approved these changes

2021-02-22 13:35 UTC, olofab commented
LGTM

2021-02-22 13:56 UTC, olofab commented on src/app/personside/visittkort/body/vergemal/Vergemal.tsx
> +    loggInfo('Vergemål omfang er ' + verge.omfang + ' og vergesakstype er ' + verge.vergesakstype);
husk å kun logge dersom vergemål er `undefined` for å kunne fange opp typer som er glemt i mappern. trenger ikke logge alle vergemål

2021-02-23 08:00 UTC, nutgaard commented on src/app/personside/visittkort/body/vergemal/Vergemal.tsx
> +        loggInfo('Vergemål omfang er ' + verge.omfang);
Trenger vi disse loggene her?

2021-02-23 08:05 UTC, nutgaard commented on src/models/person/person.ts
> +    vergemal?: Vergemal;
Tror denne skal være `vergemal: Verge[]` om det skal være samspill med backend

2021-02-23 08:08 UTC, nutgaard requested changes
Veldig mye bra her. 
Men tror typen i PersonResponse objektet er feil mtp hva backend svarer, ref: https://github.com/navikt/modiapersonoversikt/pull/1477/files#r580832773

2021-02-23 08:12 UTC, vildestefferud commented on src/app/personside/visittkort/body/vergemal/Vergemal.tsx
> +        loggInfo('Vergemål omfang er ' + verge.omfang);
Nei, jeg tenkte feil og de vil ikke gjøre det som var intensjonen så har fjernet de

2021-02-23 08:15 UTC, nutgaard commented on src/app/personside/visittkort/body/vergemal/Vergemal.tsx
> +        loggInfo('Vergemål omfang er ' + verge.omfang);
Kan være veldig kjekt med logging når man debugger. :D 
Kan legge til at `loggInfo` sender loggen til kibana også, mens `console.log` så får du det bare opp lokalt. :)

2021-02-23 09:20 UTC, olofab commented on src/app/personside/visittkort/body/vergemal/Vergemal.tsx
> +            <Normaltekst>{verge.omfang ? vergeOmfangMapper[verge.omfang] : verge.omfang}</Normaltekst>
Denne vil vel kun gjelde dersom `verge.omfang` er `undefined`? 

`vergeOmfangMapper[verge.omfang] ?? verge.omfang`

2021-02-23 10:35 UTC, nutgaard commented on src/models/person/person.ts
> +    vergemal?: Verge[];
Denne kan aldri være `null` eller `undefined`, så vi trenger ikke `?` her. 
Da slipper vi sannsynligvis unna ett par null-sjekker andre steder i koden også

2021-02-23 10:36 UTC, nutgaard commented on src/app/personside/visittkort/body/vergemal/Vergemal.tsx
> +    if (!props.vergemal || props.vergemal.length === 0) {
Er ikke denne sjekken akkurat samme som gjøres i `VergemalWrapper` Eller brukes denne ett annet sted også?

2021-02-23 12:34 UTC, nutgaard commented on src/app/personside/visittkort/body/vergemal/Vergemal.tsx
> +function VergemalWrapper(props: { vergemal?: VergeInterface[] }) {
Kan den fortsatt være undefined her?

2021-02-23 12:34 UTC, nutgaard commented on src/app/personside/visittkort/header/Etiketter/VergemålsEtikett.tsx
> +function VergemålsEtikett(props: { vergemål?: Verge[] }) {
Kan den fortsatt være undefined her?

2021-02-25 10:07 UTC, nutgaard approved these changes

2021-02-25 10:16 UTC, merged