[OPP-989] Endring i datovelger
navikt/modiapersonoversikt pull request #1491
Opened 2021-03-18 13:27 UTC by vildestefferud

Oppdaterer feilmelding på datovelger.

Legger til løsning på hvordan bruker kan fikse feilen.

![image](https://user-images.githubusercontent.com/33753494/111633674-0c1f1400-87f6-11eb-935a-001a10f04965.png)
![image](https://user-images.githubusercontent.com/33753494/111633697-13462200-87f6-11eb-9b5f-7cc8f37594e2.png)

2021-03-19 08:59 UTC, tadeankur approved these changes

2021-03-19 08:59 UTC, tadeankur commented on src/app/personside/infotabs/oppfolging/OppfolgingDatoKomponent.tsx
> +            </SkjemaelementFeilmelding>
Duplikat kode. Kan du ha bare et method her(fra og til kan sendes som string for ex.).

2021-03-22 09:03 UTC, vildestefferud commented
Oppdaterer feilmelding på datovelger.

Legger til løsning på hvordan bruker kan fikse feilen.

![image](https://user-images.githubusercontent.com/33753494/111965150-b6987f00-8af5-11eb-81ed-9f1f3ccd1bb4.png)
![image](https://user-images.githubusercontent.com/33753494/111965193-c3b56e00-8af5-11eb-8b48-3d85b147da4c.png)

2021-03-22 11:02 UTC, nutgaard commented on src/app/personside/infotabs/oppfolging/OppfolgingDatoKomponent.tsx
> +    const feilmelding = (string: String) => (
Tror jeg bare ville kvittet med denne funksjonen da vi her innfører unødvendig overhead teknisk og kognitiv, uten at vi får noen gevinster tilbake.

Mulig det er veldig personlig, men jeg syns ihvertfall det var lettere å lese når vi hadde;
```
if (!isValid(til)) {
  return (
    <SkjemaelementFeilmelding>Feilmelding her</SkjemaelementFeilmelding>
  );
}
if (!isValid(fra)) {
  return (
    <SkjemaelementFeilmelding>Feilmelding her</SkjemaelementFeilmelding>
  );
}
```

2021-03-22 11:15 UTC, nutgaard requested changes
Moment håndterer en del dato-magi som vi må erstatte selv om vi går bort moment her.

2021-03-22 11:15 UTC, nutgaard commented on src/app/personside/infotabs/oppfolging/OppfolgingDatoKomponent.tsx
> +    return dato.toLocaleDateString('en-CA');
Syns ikke vi skal basere oss på engelsk-kanadisk formattering "bare for å få det til å fungere".

2021-03-22 11:15 UTC, nutgaard commented on src/redux/oppfolging/types.ts
> +    dato.setMonth(dato.getMonth() + 1);
Dette er ikke ekvivalent med tidligere moment implementasjon;
`moment('2021-01-31').add(1, 'month').toDate().toISOString()` -> `"2021-02-27T23:00:00.000Z"`

```
const date = new Date('2021-01-31');
date.setMonth(date.getMonth() + 1);
console.log(date.toISOString()); // "2021-03-03T00:00:00.000Z"
```

I bunn og grunn så tar ikke `setMonth` hensyn til hvor mange dager en måned har, så man vil få overflow til neste måned. Det er spesielt synlig rundt februar, men vil skje i flere tilfeller.

2021-03-24 09:42 UTC, nutgaard requested changes

2021-03-24 09:42 UTC, nutgaard commented on src/app/personside/infotabs/oppfolging/OppfolgingDatoKomponent.tsx
> +        .toISOString()
Kan vel være `.format('YYYY-MM-DD')` så blir det veldig tydlig hva vi forventer til svar her.

2021-03-24 09:42 UTC, nutgaard commented on src/app/personside/infotabs/oppfolging/OppfolgingDatoKomponent.tsx
> +    if (Date.parse(fra) > Date.parse(til)) {
Tror vi skal titte litt mer på denne funksjonen, for jeg føler jeg sitter igjen med en del spørsmål. :D 

1. Hva skjer om `Date.parse` returnerer `Invalid Date` her. 
2. Trenger vi å kalle `Date.parse` 8 ganger for å sjekke to datoer?
3. Trenger vi i det hele tatt `Date.parse`, om input følger ISO8601 så skal jo disse være leksikografisk sorterbare. Så kanskje det holder å sammenligne string-verdiene. Eller kan vi få verdier som ikke følger ISO-standarden?

2021-03-24 09:42 UTC, nutgaard commented on src/redux/oppfolging/types.ts
> +            .toString(),
`.format` returnerer en `string`, så vi trenger vel ikke `toString` her

2021-03-24 10:47 UTC, nutgaard commented
Revertert merging av https://github.com/navikt/modiapersonoversikt/pull/1482 fra dev siden den blokkerte andre endringer.
Blir derfor en merge-conflict her som må løses opp i.

2021-03-24 10:57 UTC, nutgaard commented
Må merge inn denne; https://github.com/navikt/modiapersonoversikt/pull/1494/files for å få inn endringene fra dev

2021-03-29 12:13 UTC, nutgaard approved these changes

2021-03-30 06:45 UTC, olofab approved these changes

2021-04-06 11:10 UTC, merged