slettet kode som henter saker for pensjon
navikt/modiapersonoversikt pull request #1501
Opened 2021-03-30 11:59 UTC by tadeankur

2021-03-30 12:03 UTC, tadeankur commented
@nutgaard : Litt usikker om nytt module i package.json.

2021-04-06 06:40 UTC, nutgaard requested changes
Denne må vel oppdateres litt etter endringene som ble gjort i https://github.com/navikt/modiapersonoversikt/pull/1501

2021-04-06 09:33 UTC, nutgaard requested changes
Er en feilsituasjon som ikke er håndtert, som jeg tror vi burde titte på (lang kommertar der).

2021-04-06 09:33 UTC, nutgaard commented on src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx
> +    const result: FetchResult<Result> = JournalforingUtils.useSammensatteSaker(fnr);
Siden vi har gått fra to til ett api-kall, så tror jeg vi kan strømlinjeforme denne komponenten og fjerne noe av den defansive stilen som vi brukte her før.

Typisk når vi bare henter fra ett endepunkt kan vi gjøre;
```
const result: FetchResult<Result> = JournalforingUtils.useSammensatteSaker(fnr);
if (isPending(result)) {
  return <Spinner type="XL" />;
} else if (hasError(result)) {
  return (
    <AlertStripeFeil className="blokk-xxxs">
      Feilet ved uthenting av saker
    </AlertStripeAdvarsel>
  );
}

const { saker, feiledeSystemer }  = result.data;
const fordelteSaker = fordelSaker(saker);

const feiledeSystemerAlerts = feiledeSystemer.map((system) => (
  <AlertStripeAdvarsel className="blokk-xxxs" key={system}>
    Feil ved uthenting av saker fra saker fra {system}
  </AlertStripeAdvarsel>
));
```

Når vi lener oss på typesystemet på denne måten så tvinges vi til å håndtere feil-situasjoner, ved at man f.eks ikke får tilgang til `data` før man har sjekket at kallet ikke feilet. 

Per i dag så vil komponenten havne i en nokså rar state om selve rest-kallet fra `useSammensatteSaker` feiler, siden da vil `hasData` være `false`, og både `saker` og `errors` vil bestå av tomme lister.

2021-04-06 09:33 UTC, nutgaard commented on src/app/personside/journalforings-use-fetch-utils.ts
> +export function useSammensatteSaker(fnr: string, lazy: boolean = false): FetchResult<Result> {
Vi kan sikkert fjerne konseptet `sammensatte` nå? Bare rename til `useSaker` ?

2021-04-07 06:42 UTC, nutgaard requested changes
Må legge til håndtering av når selve api-kallet feiler. 
Se original kommentar for hvordan dette kan gjøres.

2021-04-07 06:42 UTC, nutgaard commented on src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx
> +    return hasData(result) ? result.data.feiledeSystemer : [];
Om api-kallet har feilet fullstendig (e.g 500 Internal Server Error eller tilsvarende), så vil `hasData` være false og man vil returnere en tom liste.

2021-04-07 06:42 UTC, nutgaard commented on src/app/personside/infotabs/meldinger/traadvisning/verktoylinje/journalforing/VelgSak.tsx
> +    } else if (getErrors(result).length > 0) {
Man må også sjekke `hasError(result)` for å sjekke om selve api-kallet feilet, det er ikke nok å sjekke `feiledesystemer`.

2021-04-07 09:40 UTC, nutgaard approved these changes

2021-04-07 09:50 UTC, merged