[OPP-874] Vaske tekstfelter
navikt/modiapersonoversikt pull request #1533
Opened 2021-04-23 10:59 UTC by vildestefferud

Bruker en regex replace til å vaske vekk ugyldige tegn når man klipper og limer inn tekst fra et tekstbehandlingsprogram inn i `Send ny Melding`.

Sånn så det ut før
![image](https://user-images.githubusercontent.com/33753494/115861871-a7c62480-a433-11eb-8e36-ab66a5489fea.png)

Slik ser ut nå etter at vi la en regex replace på tekst
![image](https://user-images.githubusercontent.com/33753494/115861732-70577800-a433-11eb-9d25-d63bc29b8bc5.png)

2021-04-23 11:24 UTC, nutgaard requested changes
Regexen vil hindre folk i å skrive ting som også er nødvendig å skrive f.eks navnet `André`, og er ikke lagt til for `FortsettDialog`.

Ville også vurdert om dette heller burde gjøres backend. Evt hvilke fordeler/ulemper vil det gi?

2021-04-23 11:24 UTC, nutgaard commented on src/app/personside/dialogpanel/sendMelding/SendNyMelding.tsx
> +                                tekst: tekst.replace(/[^a-zA-Z0-9,æøåÆØÅ!?.*<>":;/(){}|+#$¢=&%£\-[]\s]/g, '')
Denne regexen er feil tror jeg, e.g er noe mismatch av `[ ]` og litt sånn.

2021-04-23 11:32 UTC, olofab commented
En ulempe ved å legge deg backend vil vel være at meldingen de skriver blir formatert etter innsending - altså at visuelt vil meldingen endres etter innsending. Fått inntrykk av at saksbehandlere ønsker at det skal bli seende helt likt ut som det gjør i tekstfeltet

2021-04-26 12:31 UTC, nutgaard requested changes

2021-04-26 12:31 UTC, nutgaard commented on src/app/personside/dialogpanel/fortsettDialog/FortsettDialog.tsx
> +                        tekst: tekst.replace(/[^a-zA-Z0-9,àèéæøåÆØÅÀÈÉ!?.*<>":;/(){}|+#$¢@=&%£\-\][\s]/g, '')
Tror ikke denne regexen skalerer veldig godt da vi i bunn og grunn må legge til alle mulige [diakritisk tegn, ò ó ő Ö ô osv](https://no.wikipedia.org/wiki/Diakritisk_tegn)

2021-04-29 08:26 UTC, vildestefferud commented
Denne flyttes til backend.

2021-04-29 08:26 UTC, closed without merging