[PROD][OPP-1107] muligheter for å sende inn samtalereferat på samtalereferat
navikt/modiapersonoversikt pull request #1574
Opened 2021-06-04 07:53 UTC by olofab

2021-06-04 10:55 UTC, nutgaard approved these changes

2021-06-04 10:57 UTC, nutgaard requested changes
`erGyldigSamtalereferat` ser litt rar ut.

2021-06-04 10:57 UTC, nutgaard commented on src/app/personside/dialogpanel/fortsettDialog/validatorer.ts
> +            (Meldingstype.SAMTALEREFERAT_OPPMOTE && this.tekst(state))
Denne if-blokka er litt rar da `Meldingstype.SAMTALEREFERAT_OPPMOTE` aldri blir sammenligned med noe? Eller er diffen

2021-06-04 12:13 UTC, olofab commented on src/app/personside/dialogpanel/fortsettDialog/validatorer.ts
> +            (Meldingstype.SAMTALEREFERAT_OPPMOTE && this.tekst(state))
Det stemmer! Sommervarmen som har tatt knekken på meg ☀️ Jeg oppdaterer dettte!

2021-06-07 07:01 UTC, nutgaard approved these changes

2021-06-09 08:49 UTC, vildestefferud approved these changes
LGTM

2021-06-10 12:29 UTC, merged