[OPP-1498] Legger til visning når ugyldig gt gir ukjent navEnhet
navikt/modiapersonoversikt pull request #1872
Opened 2022-08-30 08:55 UTC by vildestefferud

2022-08-30 09:23 UTC, nutgaard commented on src/app/personside/visittkort-v2/body/navkontor/NavKontor.tsx
> +        if (!geografiskTilknytning) {
Trenger vi denne endringen? Om bruker ha ugyldig gt så har ting "feilet ved uthetning av informasjon om NAV-kontor"? 

Evt kan man gjøre noe alà;
```tsx
if (geografiskTilknyttning === null) {
  return (
    <Feilmelding>Fant ikke geografisk tilknyttning for bruker</Feilmelding>
  );
} else if (navEnhet === null) {
  return (
    <Feilmelding>Feilet ved uthenting av informasjon om NAV-kontor</Feilmelding>
  );
}
```

2022-08-30 09:27 UTC, nutgaard commented on src/app/personside/visittkort-v2/header/navkontor/NavKontorContainer.tsx
> +    }
Vi trenger ikke denne nøstingen her; 

```suggestion
if (person.geografiskTilknyttning === null) {
  navKontorInfo = 'NAV-kontor / Ingen enhet'
} else if (person.navEnhet === null) {
  navKontorInfo = 'NAV-kontor / ${mapUgyldigGT(person.geografiskTilknytning)}'
} else  {
  navKontorInfo = 'NAV-kontor / ${person.navEnhet.id} ${person.navEnhet.navn}'
}
```

2022-08-30 09:31 UTC, nutgaard commented on src/app/personside/visittkort-v2/visittkort-utils.ts
> +}
Bare ett alternativ for tilfeller hvor listen kanskje oppdateres oftere (ikke så relevant her):
```suggestion
const ugyldig_gt_map = {
    '0301': 'Oslo',
    '4601': 'Bergen',
    '5001': 'Tronheim',
    '1103': 'Stavanger',
};
export function mapUgyldigGT(gt: string): string {
    return ugyldig_gt_map[gt] ?? 'Ukjent';
}
```

2022-08-30 10:22 UTC, vildestefferud commented on src/app/personside/visittkort-v2/body/navkontor/NavKontor.tsx
> +        if (!geografiskTilknytning) {
Med endringene her så blir følgende visninger nå:

Hvis vi har navEnhet
<img width="458" alt="image" src="https://user-images.githubusercontent.com/33753494/187411560-f3ee0824-ae67-4e0a-a5f9-917a8ee88cd1.png">

Hvis det ikke er noen enhet og ingen geografisk tilknytning viser vi ikke det elementet lenger
<img width="619" alt="image" src="https://user-images.githubusercontent.com/33753494/187411507-90a0f0d8-0db9-45ed-80cd-f5e7e0d704e9.png">

Hvis vi ikke har noen navenhet, men vi har en geografisk tilknytning 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/33753494/187411750-9a0b4fdb-f455-494c-8541-8c5402044fc9.png">

Og hvis vi har feilende system norg 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/33753494/187412046-1cf3b15c-9767-4cd6-bf3b-572748fe5c43.png">

Så i sjekken så legger jeg inn `<VisittkortElemenet ...>` med en beskrivelse som inneholder den mappede GT'en (det blir da overskriften til elementet, og en feilmelding om at vi ikke kunne hente ut noe informasjon om NAV-kontor. Kan muligens endre noe på selve feilmeldingen her så den skiller seg bedre fra feilende system feilmeldingen. Ellers viser jeg feilmelding når vi har feilende system, ingenting hvis vi hverken har navEnhet eller gt og hvis vi har navenhet så viser vi publikumsmottaket. 
Jeg har gjort det slik siden det på morgenmøte i går ble ytret at det er ønskelig å vise feks Oslo hvis bydel mangler slik at vi ikke får hentet ut publikumsmottak. 
Jeg tenkte at denne sjekken ville holde det mest mulig likt slik det var fra før.

2022-08-30 11:59 UTC, nutgaard approved these changes

2022-08-30 13:01 UTC, eirikdahlen requested changes
Tror vi burde fikse typoen før den går ut hvertfall 👍🏼

2022-08-30 13:01 UTC, eirikdahlen commented on src/app/personside/visittkort-v2/visittkort-utils.ts
> +    '5001': 'Tronheim',
Typo i Trondheim*
Og så er jeg kanskje mer fan av camelCase på variabelnavn 🤔

2022-08-31 06:32 UTC, nutgaard approved these changes

2022-08-31 07:17 UTC, eirikdahlen approved these changes

2022-09-01 06:39 UTC, merged