[OPP-1526] Legg til lestdato på journalpost element
navikt/modiapersonoversikt pull request #2000
Opened 2022-12-06 12:40 UTC by Jesperpaulsen

Avhengig av: https://github.com/navikt/modiapersonoversikt-api/pull/1034

2022-12-06 14:30 UTC, nutgaard commented
LGTM, men tror vi bør avklare spørsmålet ditt med dokument-gjengen før denne går ut i prod.


Pluss en liten nitpick; ingen grunn til at package-lock skal endre seg i denne PRen ;)

2022-12-07 07:44 UTC, abrhanav approved these changes

2022-12-08 09:10 UTC, nutgaard requested changes
Request Changes er bare for å hindre at vi merger før vi har fått avklaringen rundt hva vi gjør med eldre dokumenter.

2022-12-13 14:01 UTC, Jesperpaulsen commented
Viser nå kun "Lest <DATO>" for saker vi har lest dato på. Resten som enten ikke er lest, eller som vi ikke har lest dato på vises ikke.

2022-12-13 14:05 UTC, nutgaard commented on src/app/personside/infotabs/saksoversikt/saksdokumenter/JournalPostListeElement/JournalpostLestAvBruker.tsx
> +    return (
Om `lestDato === null` så vil vi fortsatt spytte ut en del html her tror jeg.
Noe alà; 
```html
<div>
  <p>
    <div></div>
  </p>
</div>
```

Så tenker vi kan legge inn en liten guard for det, og forenkle html'en samtidig ;)

2022-12-13 14:24 UTC, merged