[OPP-1527] Automatisk slå opp aktiv ident ved oppslag på inaktiv ident
navikt/modiapersonoversikt pull request #2007
Opened 2022-12-12 14:52 UTC by abrhanav

2022-12-12 14:59 UTC, nutgaard commented on src/rest/resources/tilgangskontrollResource.tsx
> +    aktivIdent?: string;
Finnes det tilfeller hvor `harTilgang == true` og `aktivIdent` ikke er satt?

2022-12-12 15:03 UTC, nutgaard commented on src/app/personside/NyIdentModal.tsx
> +            </div>
Trenger ikke å bruke string templates her
```suggestion
            <div className="noncenter typo-normal blokk-m">
                Personidenten du slo opp er ikke lenger aktive. Ny ident for bruker er {props.aktivIdent}.
            </div>
```

2022-12-12 15:04 UTC, nutgaard commented on src/app/personside/NyIdentModal.tsx
> +            <Knapp type="hoved" className="blokk-xxxs" onClick={(e) => handleClick()}>
[NITPICK]
```suggestion
            <Knapp type="hoved" className="blokk-xxxs" onClick={handleClick}>
```

2022-12-12 15:05 UTC, nutgaard commented on src/app/personside/NyIdentModal.tsx
> +            <Knapp type="hoved" className="blokk-xxxs" onClick={(e) => handleClick()}>
Men kanskje dette heller burde vært en lenke? 🤔

2022-12-12 15:07 UTC, nutgaard requested changes
Om jeg forstår ting rett så vil modalen alltid vises. Uavhengig av om man slår opp aktiv ident eller ikke.

2022-12-13 13:35 UTC, Jesperpaulsen approved these changes
<img src="https://media3.giphy.com/media/13zeE9qQNC5IKk/giphy.gif"/>

2022-12-13 13:35 UTC, Jesperpaulsen commented on src/app/personside/NyIdentModal.tsx
> +                Personidenten du slo opp er ikke lenger aktive. Ny ident for bruker er {props.aktivIdent}.
```suggestion
                Personidenten du slo opp er ikke lenger aktiv. Ny ident for bruker er {props.aktivIdent}.
```

2022-12-13 14:00 UTC, nutgaard requested changes
Ønsker at vi bruker react-router sine lenker slik at vi slipper en full relasting av siden ved redirect

2022-12-13 14:00 UTC, nutgaard commented on src/app/personside/NyIdentModal.tsx
> +    const [open, setOpen] = useState(true);
Trenger vi egentlig state her? Modalen skal vel aldri kunne lukkes?

2022-12-14 12:57 UTC, nutgaard approved these changes

2022-12-19 13:12 UTC, merged